heading: "Why Choose Traxis Manufacturing?"
subheading: "We combine state-of-the-art precision technology with accessible, expert-driven human partnership to deliver exceptional results."
services:
  - title: "Capabilities"
    description: "Advanced CNC milling and turning capabilities for complex geometries and tight tolerances across various materials."
    icon: "mdi:cog-outline"
    link: "/capabilities"
    buttonText: "View Capabilities"
  - title: "Our Work"
    description: "Explore our portfolio of precision-machined components for aerospace, medical, and industrial applications."
    icon: "mdi:briefcase-variant-outline"
    link: "/work"
    buttonText: "See Portfolio"
  - title: "Our Process"
    description: "Learn about our collaborative approach from design review to final delivery, ensuring quality at every step."
    icon: "mdi:clipboard-list-outline"
    link: "/process"
    buttonText: "Our Workflow"
  - title: "About Us"
    description: "Meet our dedicated team of expert machinists and learn about our Austin-based facility and commitment to quality."
    icon: "mdi:account-group-outline"
    link: "/about"
    buttonText: "Meet Our Team"