heading: "Precision Milling Excellence"
paragraphs:
  - "Our CNC milling services combine state-of-the-art equipment with decades of machining expertise to produce complex components with exceptional precision. From simple brackets to intricate aerospace components, we handle projects that demand the highest levels of accuracy and quality."
  - "Whether you need prototypes for design validation or medium-volume production runs, our milling capabilities ensure consistent quality and dimensional accuracy that meets the most stringent requirements."
image:
  src: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop&crop=center"
  alt: "High-precision CNC milling machine in operation"
capabilities:
  - text: "Tolerances as tight as ±0.001\""
    icon: "mdi:check-circle"
  - text: "Complex 3D contours and geometries"
    icon: "mdi:check-circle"
  - text: "Thin-wall and deep-pocket machining"
    icon: "mdi:check-circle"
  - text: "Multiple setups minimized with 5-axis capability"
    icon: "mdi:check-circle"