heading: "Common Turning Applications"
applications:
  - title: "Shafts & Rods"
    description: "Precision shafts for mechanical assemblies"
    icon: "mdi:circle-outline"
  - title: "Bushings & Sleeves"
    description: "Cylindrical components with tight ID/OD tolerances"
    icon: "mdi:pipe"
  - title: "Threaded Components"
    description: "Precision threads and fasteners"
    icon: "mdi:screw-machine-round-top"
  - title: "Medical Devices"
    description: "Surgical instruments and implant components"
    icon: "mdi:medical-bag"